api_platform:
    title: Symfony 7 API REST
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    collection:
        pagination:
            enabled: true
            page_parameter_name: _page
